// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0-MA9D4Ia1IT6_jNCQs9JYWVstZBd19k',
    appId: '1:50489619840:web:aa72936d0ab4461b843d65',
    messagingSenderId: '50489619840',
    projectId: 'examenu3-b6f08',
    authDomain: 'examenu3-b6f08.firebaseapp.com',
    storageBucket: 'examenu3-b6f08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcb8MdDM405pZGwe1my-_cxi_xbJtOYEQ',
    appId: '1:50489619840:android:18f28e1974cd1019843d65',
    messagingSenderId: '50489619840',
    projectId: 'examenu3-b6f08',
    storageBucket: 'examenu3-b6f08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbBmaoQo72mbom3SC7qcDoG2eaqn-FRnE',
    appId: '1:50489619840:ios:a1299eac9ba15948843d65',
    messagingSenderId: '50489619840',
    projectId: 'examenu3-b6f08',
    storageBucket: 'examenu3-b6f08.firebasestorage.app',
    iosBundleId: 'com.example.examenU3App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbBmaoQo72mbom3SC7qcDoG2eaqn-FRnE',
    appId: '1:50489619840:ios:a1299eac9ba15948843d65',
    messagingSenderId: '50489619840',
    projectId: 'examenu3-b6f08',
    storageBucket: 'examenu3-b6f08.firebasestorage.app',
    iosBundleId: 'com.example.examenU3App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0-MA9D4Ia1IT6_jNCQs9JYWVstZBd19k',
    appId: '1:50489619840:web:d34235fd45950b0c843d65',
    messagingSenderId: '50489619840',
    projectId: 'examenu3-b6f08',
    authDomain: 'examenu3-b6f08.firebaseapp.com',
    storageBucket: 'examenu3-b6f08.firebasestorage.app',
  );
}
